language: android

jdk:
  - oraclejdk8
  
env:
  global:
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2
    - ADB_INSTALL_TIMEOUT=20 # install timeout in minutes (2 minutes by default)
  matrix:
    - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a
    
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install new Android SDK tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - $ANDROID_TARGET
    - android-25

    # Support library
    - extra-android-support
    - extra-android-m2repository

before_script:
  - chmod +x ./gradlew
  
script:
  - ./gradlew clean build

after_success:
  - bash <(curl -s https://codecov.io/bash)
